const counterConstant = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    INITCOUNTER: 'INITCOUNTER',
    INITCOUNTERSUCCESS: 'INITCOUNTERSUCCESS',
    UPDATECOUNTER: 'UPDATECOUNTER',
    UPDATECOUNTERSUCCESS: 'UPDATECOUNTERSUCCESS',
    COPYCOUNTER: 'COPYCOUNTER',
    SETNORMALDATATYPE: 'SETNORMALDATATYPE'
}

module.exports = counterConstant;