const counterConstant = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    INITCOUNTERSUCCESS: 'INITCOUNTERSUCCESS',
    UPDATECOUNTERSUCCESS: 'UPDATECOUNTERSUCCESS',
    COPYCOUNTER: 'COPYCOUNTER',
    SETNORMALDATATYPE: 'SETNORMALDATATYPE'
}

module.exports = counterConstant;