const globalConstant = {
    VIEWROTATE: 'VIEWROTATE',
    VIEWCHANGESIZE: 'VIEWCHANGESIZE',
    THEMECHANGE: 'THEMECHANGE',
    SCROLLTOPOSITION: 'SCROLLTOPOSITION',
}

module.exports = globalConstant;