const timerConstant = {
    COUNTDOWN: 'COUNTDOWN',
    RESETTIMER: 'RESETTIMER',
    CHANGETIMESPANTODEFAULT: 'CHANGETIMESPANTODEFAULT',
    CHNAGETIMESPANTOCOUNTER: 'CHNAGETIMESPANTOCOUNTER'
}

module.exports = timerConstant;